name: peminjam_perpustakaan_kelas_c
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  http: ^1.1.0
  get: ^4.6.5
  date_time_picker: ^2.1.0
  flutter_carousel_widget: ^2.2.0
  visibility_detector: ^0.2.0
  animated_splash_screen: 1.3.0
  google_fonts: ^4.0.4
  image_picker: ^0.8.4+3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

